os:
  editPreset: "nvim-remote"
gui:
  nerdFontsVersion: "3"
  sidePanelWidth: 0.2 # gives you more space to show things side-by-side
git:
  autoFetch: false
  pagers:
    - colorArg: always
      pager: delta --dark --paging=never --line-numbers --hyperlinks --hyperlinks-file-link-format="lazygit-edit://{path}:{line}"
